sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t lavisht22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lavisht22/docker-react npm run test -- --coverage
