sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t lavisht22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lavisht22/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-594277190649"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
